# Generated by Django 4.2.7 on 2026-05-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='telebirr_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
