# Generated by Django 4.2.7 on 2026-05-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('telebirr', 'Telebirr'), ('cbe', 'CBE Bank Transfer'), ('other', 'Other Bank Transfer')], default='', max_length=20),
        ),
    ]
