# Generated by Django 4.2.7 on 2026-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('telebirr', 'Telebirr'), ('cbe', 'CBE Bank Transfer'), ('other', 'Other Bank Transfer')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
