# Generated by Django 4.2.7 on 2026-05-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_am',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
