# Generated by Django 6.0.5 on 2026-06-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_category_name_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('slightly_used', 'Slightly Used'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=15),
        ),
    ]
