# Generated by Django 4.2.7 on 2026-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=60)),
                ('account_holder', models.CharField(blank=True, max_length=120)),
                ('telebirr', models.CharField(blank=True, max_length=30)),
                ('mobile_money', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Platform Settings',
            },
        ),
    ]
